common/models/Booking.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "booking".
 *
 * @property int $id_booking
 * @property int|null $id_user
 * @property int|null $id_kost
 * @property int|null $id_penghuni
 * @property int|null $id_hitungan
 * @property int|null $id_durasi
 * @property string|null $tgl_masuk
 * @property string|null $created_time
 * @property string|null $modified_time
 */
class Booking extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'booking';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'id_kost', 'id_penghuni', 'id_hitungan', 'id_durasi','status'], 'integer'],
            [['tgl_masuk', 'created_time', 'modified_time'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Id Booking',
            'id_user' => 'User',
            'id_kost' => 'Kost',
            'id_penghuni' => 'Penghuni',
            'id_hitungan' => 'Hitungan Sewa',
            'id_durasi' => 'Durasi Sewa',
            'tgl_masuk' => 'Tgl Masuk',
            'status' => 'Status',
            'created_time' => 'Created Time',
            'modified_time' => 'Modified Time',
        ];
    }
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }
    public function getKost()
    {
        return $this->hasOne(Kost::className(), ['id' => 'id_kost']);
    }
    public function getPenghuni()
    {
        return $this->hasOne(Penghuni::className(), ['id' => 'id_penghuni']);
    }
    public function getHitunganSewa()
    {
        return $this->hasOne(HitunganSewa::className(), ['id' => 'id_hitungan']);
    }
    public function getDurasiSewa()
    {
        return $this->hasOne(DurasiSewa::className(), ['id' => 'id_durasi']);
    }
}

backend/controllers/BookingController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Booking;
use common\models\BookingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use dominus77\sweetalert2\Alert;
/**
 * BookingController implements the CRUD actions for Booking model.
 */
class BookingController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Booking models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Booking model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Booking model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Booking();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Booking model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    public function actionKonfirm($id)
    {
        $model = $this->findModel($id);
            $model->status = 1;
            $model->save(false);
            Yii::$app->session->setFlash(\dominus77\sweetalert2\Alert::TYPE_SUCCESS, [
                [
                    'title' => 'Selamat Anda Telah Berhasil Booking!!!',
                    'text' => 'Silahkan menunggu verifikasi booking Anda',
                    'confirmButtonText' => 'Done!',
                ]
             ]);
            return $this->redirect(['index']);
    }
    /**
     * Deletes an existing Booking model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Booking model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Booking the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Booking::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/booking/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Booking */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="booking-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_user')->textInput() ?>

    <?= $form->field($model, 'id_kost')->textInput() ?>

    <?= $form->field($model, 'id_penghuni')->textInput() ?>

    <?= $form->field($model, 'id_hitungan')->textInput() ?>

    <?= $form->field($model, 'id_durasi')->textInput() ?>

    <?= $form->field($model, 'tgl_masuk')->textInput() ?>

    <?= $form->field($model, 'created_time')->textInput() ?>

    <?= $form->field($model, 'modified_time')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/booking/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\BookingSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="booking-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_user') ?>

    <?= $form->field($model, 'id_kost') ?>

    <?= $form->field($model, 'id_penghuni') ?>

    <?= $form->field($model, 'id_hitungan') ?>

    <?php // echo $form->field($model, 'id_durasi') ?>

    <?php // echo $form->field($model, 'tgl_masuk') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <?php // echo $form->field($model, 'modified_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/booking/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Booking */

$this->title = 'Create Booking';
$this->params['breadcrumbs'][] = ['label' => 'Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="booking-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/booking/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use dominus77\sweetalert2\Alert;
/* @var $this yii\web\View */
/* @var $searchModel common\models\BookingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Bookings';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="booking-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'id_user',
                'value' => function($model){
                    if($model->user != NULL){
                    return $model->user->username;
                    }
                },
                'label' => 'User'
            ],
            [
                'attribute' => 'id_kost',
                'value' => function($model){
                    if($model->kost != NULL){
                    return $model->kost->nama_kost;
                    }
                },
                'label' => 'Kost'
            ],
            [
                'attribute' => 'id_penghuni',
                'value' => function($model){
                    if($model->penghuni != NULL){
                    return $model->penghuni->nama_lengkap;
                    }
                },
                'label' => 'Penghuni'
            ],
            [
                'attribute' => 'id_hitungan',
                'value' => function($model){
                    if($model->hitunganSewa != NULL){
                    return $model->hitunganSewa->hitungan_sewa;
                    }
                },
                'label' => 'Hitungan Sewa'
            ],
            [
                'attribute' => 'status',
                'value' => function($model){
                    if($model->status == 0){
                    return 'Belum Dikonfirmasi';
                    }else{
                    return 'Sudah Dikonfirmasi';
                    }
                },
                'label' => 'Status'
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{confirm}',
                'contentOptions' => ['style'=>'text-align: center'],
                'buttons' => [
                    'confirm' => function($url, $model, $key){
                        if($model->status == 0){
                        return Html::a(Yii::t('app','{modelClass}',['modelClass'=>'Konfirmasi']),['booking/konfirm','id'=>$model->id], ['class' => 'btn btn-success modalButtonView']);
                        }
                    },
                    
                ],
            ],
            //'id_durasi',
            //'tgl_masuk',
            //'created_time',
            //'modified_time',

           
        ],
    ]); ?>


</div>

backend/views/booking/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Booking */

$this->title = 'Update Booking: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="booking-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/booking/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Booking */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="booking-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'id_user',
            'id_kost',
            'id_penghuni',
            'id_hitungan',
            'id_durasi',
            'tgl_masuk',
            'created_time',
            'modified_time',
        ],
    ]) ?>

</div>