common/models/Kost.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "kost".
 *
 * @property int $id_kost
 * @property int|null $id_tipe
 * @property int|null $id_kategori
 * @property int|null $id_kota
 * @property string|null $nama_kost
 * @property string|null $deskripsi
 * @property string|null $luas_kamar
 * @property string|null $fasilitas
 * @property string|null $harga
 * @property string|null $lokasi
 * @property string|null $gambar
 * @property string|null $created_time
 * @property string|null $modified_time
 */
class Kost extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'kost';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_tipe', 'id_kategori', 'id_kota'], 'integer'],
            [['deskripsi', 'lokasi'], 'string'],
            [['created_time', 'modified_time'], 'safe'],
            [['nama_kost', 'fasilitas', 'harga'], 'string', 'max' => 100],
            [['luas_kamar'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_kost' => 'Id Kost',
            'id_tipe' => 'Tipe Kos',
            'id_kategori' => 'Kategori Kos',
            'id_kota' => 'Kota',
            'nama_kost' => 'Nama Kost',
            'deskripsi' => 'Deskripsi',
            'luas_kamar' => 'Luas Kamar',
            'fasilitas' => 'Fasilitas',
            'harga' => 'Harga',
            'lokasi' => 'Lokasi',
            'gambar' => 'Gambar',
            'created_time' => 'Created Time',
            'modified_time' => 'Modified Time',
        ];
    }
     /**
     * @return \yii\db\ActiveQuery
     */
     public function getTipeKost()
     {
         return $this->hasOne(TipeKost::className(), ['id' => 'id_tipe']);
     }
 
     /**
      * @return \yii\db\ActiveQuery
      */
     public function getKategoriKost()
     {
         return $this->hasOne(KategoriKost::className(), ['id' => 'id_kategori']);
     }
 
     /**
      * @return \yii\db\ActiveQuery
      */
     public function getKota()
     {
         return $this->hasOne(Kota::className(), ['id' => 'id_kota']);
     }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\User;
use common\models\Penghuni;
use common\models\Booking;
use common\models\Kost;
use common\models\TipeKost;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $sumpenghuni = Penghuni::find()->count();
        $sumuser = User::find()->count();
        $sumbooking = Booking::find()->count();
        $sumkost = Kost::find()->count();
        $tipekost = TipeKost::find();
        $tipekostputra = Kost::find()->where(['id_tipe' => 1])->count();
        $tipekostputri = Kost::find()->where(['id_tipe' => 2])->count();
        $tipekostcampur = Kost::find()->where(['id_tipe' => 3])->count();
        return $this->render('index',[
            'sumpenghuni' => $sumpenghuni,
            'sumuser' => $sumuser,
            'sumbooking' => $sumbooking,
            'sumkost' => $sumkost,
            'tipekostcampur' => $tipekostcampur,
            'tipekostputri' => $tipekostputri,
            'tipekostputra' => $tipekostputra,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\helpers\ArrayHelper;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\Kost;
use common\models\Kota;
use common\models\TipeKost;
use common\models\KategoriKost;
use common\models\HitunganSewa;
use common\models\DurasiSewa;
use common\models\Booking;
use common\models\Penghuni;
use common\models\User;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {       
        $this->layout = 'main.php';
        $kota = Kota::find()->limit(8)->orderBy('id DESC')->all();
        $kost = Kost::find()->limit(6)->orderBy('id DESC')->all();
        $datalist = ArrayHelper::map(KategoriKost::find()->all(), 'id', 'nama_kategori');
        $datalistkota = ArrayHelper::map(Kota::find()->all(), 'id', 'nama_kota');
        return $this->render('index',[
            'kost' => $kost,
            'kota' => $kota,
            'datalist' => $datalist,
            'datalistkota' => $datalistkota
        ]);
    }
    public function actionKostsearch()
    {
        $name = Yii::$app->request->get('qsearch');
        $kategori = Yii::$app->request->get('nama_kategori');
        $kota = Yii::$app->request->get('nama_kota');
        $kost = Kost::find()->where(['LIKE', 'nama_kost', $name])
            ->andWhere(['LIKE', 'id_kategori', $kategori])
            ->andWhere(['LIKE', 'id_kota', $kota])
            ->all();
        $datalist = ArrayHelper::map(KategoriKost::find()->all(), 'id', 'nama_kategori');
        $datalistkota = ArrayHelper::map(Kota::find()->all(), 'id', 'nama_kota');
        //var_dump($models);
        return $this->render('kost', [
            'kost' => $kost,
            'datalist' => $datalist,
            'datalistkota' => $datalistkota,
           //  'dataProvider' => $dataProvider
            
    
       ]);
    }  
    /**
     * Displays kost.
     *
     * @return mixed
     */
     public function actionKost()
     {       
 
         $kota = Kota::find()->limit(8)->orderBy('id DESC')->all();
         $kost = Kost::find()->orderBy('id DESC')->all();
         $datalist = ArrayHelper::map(KategoriKost::find()->all(), 'id', 'nama_kategori');
         $datalistkota = ArrayHelper::map(Kota::find()->all(), 'id', 'nama_kota');
         return $this->render('kost',[
             'kost' => $kost,
             'kota' => $kota,
             'datalist' => $datalist,
             'datalistkota' => $datalistkota
         ]);
     }
      /**
     * Displays detailkost.
     *
     * @return mixed
     */
     public function actionDetailkost($id)
     {       
        $model = $this->findModel($id);
         $kota = Kota::find()->limit(8)->orderBy('id DESC')->all();
         $tipe = TipeKost::find()->all();
         $kategori = KategoriKost::find()->all();
         $detailkos = Kost::findOne($id);

         return $this->render('detailkost',[
             'detailkos' => $detailkos,
             'kota' => $kota,
             'kategori' => $kategori,
             'tipe' => $tipe
         ]);
     }

     /**
     * Displays kota.
     *
     * @return mixed
     */
     public function actionArtikel()
     {       

         $kota = Kota::find()->orderBy('id DESC')->all();
         $kost = Kost::find()->orderBy('id DESC')->all();
         return $this->render('artikel',[
             'kost' => $kost,
             'kota' => $kota
         ]);
     }
     /**
     * Displays kota.
     *
     * @return mixed
     */
     public function actionProfil($id)
     {       
        $histori = Booking::find()->where(['id_user'=>$id])->all();
         $historipenghuni = Booking::find()->where(['id_user'=>$id])->one();
         $penghuni = Penghuni::find()->where(['id' => $historipenghuni->id_penghuni])->one();
         $profile = User::findOne($id);
         return $this->render('profil',[
             'profile' => $profile,
             'historipenghuni' => $historipenghuni,
             'penghuni' => $penghuni,
             'histori' => $histori
         ]);
     }
     public function actionFasilitas($id)
     {       
        $kota = Kota::find()->limit(8)->orderBy('id DESC')->all();
        $kost = Kost::find()->where(['id_kategori'=>$id])->all();
        $datalist = ArrayHelper::map(KategoriKost::find()->all(), 'id', 'nama_kategori');
        $datalistkota = ArrayHelper::map(Kota::find()->all(), 'id', 'nama_kota');
        return $this->render('kost',[
            'kost' => $kost,
            'kota' => $kota,
            'datalist' => $datalist,
            'datalistkota' => $datalistkota
        ]);
     }
     public function actionKota($id)
     {       
        $kota = Kota::find()->limit(8)->orderBy('id DESC')->all();
        $kost = Kost::find()->where(['id_kota'=>$id])->all();
        $datalist = ArrayHelper::map(KategoriKost::find()->all(), 'id', 'nama_kategori');
        $datalistkota = ArrayHelper::map(Kota::find()->all(), 'id', 'nama_kota');
        return $this->render('kost',[
            'kost' => $kost,
            'kota' => $kota,
            'datalist' => $datalist,
            'datalistkota' => $datalistkota
        ]);
     }
      /**
     * Displays kota.
     *
     * @return mixed
     */
     public function actionBooking($id)
     {  
        if(!Yii::$app->user->isGuest){
        $cekuser = Yii::$app->user->identity->id;
        $sewa = HitunganSewa::find()->all();
        $durasi = DurasiSewa::find()->all();
        $penghuni = new Penghuni();
        $booking = new Booking();
       
                if ($penghuni->load(Yii::$app->request->post()) && $booking->load(Yii::$app->request->post())) {
                    $transaction = Yii::$app->db->beginTransaction();
                    $hasilpenghuni = $penghuni->save();
                    if($hasilpenghuni){
                        $modelBooking = new Booking();
                        $modelBooking->id_user =  $cekuser;
                        $modelBooking->id_kost =  $id;
                        $modelBooking->id_penghuni =  $penghuni->id;
                        $modelBooking->id_hitungan =  $booking->id_hitungan;
                        $modelBooking->id_durasi =  $booking->id_durasi;
                        $date = date_create($booking->tgl_masuk);
                        $dateFix = date_format($date, 'Y-m-d');
                        $modelBooking->tgl_masuk = $dateFix;
                        $modelBooking->status = 0;
                        $resultbooking = $modelBooking->save(false);
                        $transaction->commit();
                        
                        Yii::$app->session->setFlash(\dominus77\sweetalert2\Alert::TYPE_SUCCESS, [
                           [
                               'title' => 'Selamat Anda Telah Berhasil Booking!!!',
                               'text' => 'Silahkan menunggu verifikasi booking Anda',
                               'confirmButtonText' => 'Done!',
                           ]
                        ]);
                        return $this->redirect(['site/index']);
                    }
                    }
        
                return $this->render('booking', [
                    'penghuni' => $penghuni,
                    'booking' => $booking,
                    'sewa' => $sewa,
                    'durasi' => $durasi,
                ]);
     }else{
        Yii::$app->session->setFlash('error', 'Anda harus Login Terlebih Dahulu');
     }
    }
     /**
     * Displays kota.
     *
     * @return mixed
     */
     public function actionKonfirmBooking($id)
     {          
        $sewa = HitunganSewa::find()->all();
        $durasi = DurasiSewa::find()->all();
        $penghuni = new Penghuni();
        $booking = new Booking();
                if ($model->load(Yii::$app->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
        
                return $this->render('booking', [
                    'model' => $model,
                    'model' => $sewa,
                    'model' => $durasi,
                ]);
     }
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

frontend/views/site/detailkost.php
<?php
  use yii\helpers\Html;
  use yii\helpers\Url;
?>
<section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image: url('../images/bg_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
          <div class="row slider-text align-items-end">
            <div class="col-md-10 col-sm-12 ftco-animate mb-4">
              <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a href="#">Kos</a></span> <span>Detail Kos</span></p>
              <h1 class="mb-3">Detail Kos</h1>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">
            <h2 class="mb-3"><?= $detailkos->nama_kost ?></h2>
            <p>Untuk <?= $detailkos->tipeKost->nama_tipe ?></p>
            <p>
            <a href="" class="img-fluid"><?= Html::img(Yii::$app->urlManagerBackend->baseUrl . '/images/'.$detailkos->gambar) ?></a><br>
            </p>
            <h6>Tipe Tempat Tinggal</h6>
            <h5><?= $detailkos->kategoriKost->nama_kategori ?></h5><br>
          
           <h6>Luas Kamar</h6>
           <h5><?= $detailkos->luas_kamar ?></h5><br>
            
            <h6>Deskripsi</h6>
            <h5><?= $detailkos->deskripsi ?></h5><br>
            <h6>Deskripsi</h6>
            <h5><?= $detailkos->fasilitas ?></h5><br>
           <h6>Lokasi Alamat Kos</h6>
           <h5><?= $detailkos->lokasi ?></h5><br>
            
            <div class="pt-5 mt-5">
              
              
              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Tinggalkan Komentar</h3>
                <form action="#" class="p-5 bg-light">
                  <div class="form-group">
                    <label for="name">Nama *</label>
                    <input type="text" class="form-control" id="name">
                  </div>
                  <div class="form-group">
                    <label for="email">Email *</label>
                    <input type="email" class="form-control" id="email">
                  </div>

                  <div class="form-group">
                    <label for="message">Pesan</label>
                    <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                  </div>

                </form>
              </div>
            </div>

          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar">
          <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Booking</h3>
                <p>Data bisa berubah sewaktu-waktu</p>
                <li><p>Harga : <h4>Rp. <?= $detailkos->harga ?>,-</h4></p><br></li>
                <li>Tidak Termasuk Listrik</li>
                <li>Tidak ada min.pembayaran<br></li>
                <?php
                if(Yii::$app->user->isGuest){
                ?>
                <a href="#"><button class="btn btn-primary py-2 px-4" data-toggle="modal" data-target="#bookingModalCenter">Booking</button></a> | <a href="#"><button class="btn btn-primary py-2 px-4" data-toggle="modal" data-target="#exampleModalCenter">Hubungi Kost</button></a>
                <?php
                }else{
                ?>
                <a href="<?= Url::toRoute(['site/booking', 'id' => $detailkos->id]); ?>"><button class="btn btn-primary py-2 px-4">Booking</button></a> | <a href="#"><button class="btn btn-primary py-2 px-4" data-toggle="modal" data-target="#exampleModalCenter">Hubungi Kost</button></a>
                <?php
                }
                ?>
              </div>
            </div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Hubungi Kost</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <p>Mohon maaf saat ini pemilik kost sedang offline. Maka dari itu silahkan menghubungi nomor yang ada dibawah ini</p><br>
         <p>Pemilik Kost : 085732424234 <br>
         Admin : 082290037810</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="bookingModalCenter" tabindex="-1" role="dialog" aria-labelledby="bookingModalCenter" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-contentbooking">
      <div class="modal-header">
        <h5 class="modal-title" id="bookingModalCenter">Warning</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <p>Mohon Maaf Anda Harus Login Terlebih Dahulu</p>
      </div>
      <div class="modal-footer">
        <a href="<?= Url::toRoute(['site/login']); ?>"><button type="button" class="btn btn-primary">Login</button></a>
      </div>
    </div>
  </div>
</div>     
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Kategori</h3>
                <?php
                    if ($kategori) {
                    foreach ($kategori as $kategorikos => $resultkategori) {

                    ?>
                <li><a href="#"><?= $resultkategori->nama_kategori ?> <span>~</span></a></li>
               <?php
                    }
                }
               ?>
              </div>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Tipe Kos</h3>
                <?php
                    if ($tipe) {
                    foreach ($tipe as $tipekos => $resulttipe) {

                    ?>
                <li><a href="#"><?= $resulttipe->nama_tipe ?> <span>~</span></a></li>
               <?php
                    }
                }
               ?>
               
              </div>
            </div>

            

            <div class="sidebar-box ftco-animate">
              <h3>Ana Kos</h3>
              <p>Platform digital penyedia Informasi dan Booking tempat tinggal bagi Anak Kost</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/fasilitas.php
<?php
  use yii\helpers\Html;
  use yii\helpers\Url;
  use yii\bootstrap\ActiveForm;
?>
<section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image: url('../../images/bg_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
          <div class="row slider-text align-items-end">
            <div class="col-md-10 col-sm-12 ftco-animate mb-4">
              <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Layanan Kos</span></p>
              <h1 class="mb-3">Layanan Kos</h1>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="ftco-section-reservation">
<div class="container">
  <div class="row justify-content-end ftco-animate">
    <div class="col-lg-4 col-md-5 reservation p-md-5">
      <div class="block-17">
      <?php $form = ActiveForm::begin(['id' => 'form-search',
                                    'action' => ['site/kostsearch'],
                                    'class' => ['d-block'],
                                    'method' => 'get',
                                    'options' => ['method' => 'get'],
                                ]); ?>
       
          <div class="fields d-block">

            <!-- <div class="book-date one-third">
              <label for="check-in">Check in:</label>
              <input type="text" id="checkin_date" class="form-control" placeholder="M/D/YYYY">
            </div>

            <div class="book-date one-third">
              <label for="check-out">Check out:</label>
              <input type="text" id="checkout_date" class="form-control" placeholder="M/D/YYYY">
            </div> -->
            <div class="book-date one-third">
              <label for="check-out">Pencarian Ana Kos</label>
              <input type="text" class="form-control" name="qsearch" placeholder="Cari sesuai dengan Keinginan Anda">
            </div> 
            <div class="one-third">
              <label for="Guest">Kota</label>
              <div class="select-wrap">
                <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                <?=Html::dropDownList('nama_kota', $selection= NULL, $datalistkota,['prompt'=>'Pilih Kota', 'class' => 'form-control']);?>
              </div>
            </div>
            <div class="one-third">
              <label for="Guest">Filter</label>
              <div class="select-wrap">
                <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                <?=Html::dropDownList('nama_kategori', $selection= NULL, $datalist,['prompt'=>'Pilih Kategori Kos', 'class' => 'form-control']);?>
              </div>
            </div>
          </div>
          <?= Html::submitButton('Cari', ['class' => 'search-submit btn btn-primary', 'name' => 'signup-button']) ?> 
          <?php $form = ActiveForm::end(); ?> 
      </div>
    </div>
  </div>
</div>
</div>

    <section class="ftco-section room-section bg-light">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-5">
          <div class="col-md-7 text-center heading-section ftco-animate">
            <span class="subheading">Layanan Kos</span>
            <h2>Informasi dan Booking tempat tinggal sesuai dengan keinginan Anda</h2>
            <?php
                if($kost == Null){
                ?>

<h3>Tidak Ada Data. Silahkan Cek Pencarian Anda</h3>
                <?php
                }
                ?>
          </div>
        </div>
        <div class="row">
      
        <?php
      foreach ($kost as $datakost => $resultkost) {

    ?>
          <div class="col-md-4 ftco-animate">
            <div class="room-wrap">
              <a href="#" class="room-img"><?= Html::img(Yii::$app->urlManagerBackend->baseUrl . '/images/' . $resultkost->gambar) ?></a>
              <div class="text p-4">
                <div class="d-flex mb-1">
                  <div class="one-third">
                    <p class="star-rate"><span class="icon-star"></span><span class="icon-star"></span><span class="icon-star"></span><span class="icon-star"></span><span class="icon-star-half-full"></span></p>
                    <h3><a href="#"><?= $resultkost->nama_kost ?></a></h3>
                  </div>
                  <div class="one-forth text-center">
                    <p class="price"><?= $resultkost->harga ?><br><span>/Bulanan</span></p>
                  </div>
                </div>
                <p class="features">
                <span class="d-block mb-2"><i class="icon-check mr-2"></i> Kasur</span>
                <span class="d-block mb-2"><i class="icon-check mr-2"></i> Lemari Pakaian</span>
                <span class="d-block mb-2"><i class="icon-check mr-2"></i> Wifi Internet</span>
                <span class="d-block mb-2"><i class="icon-check mr-2"></i> Kamar Mandi</span>
                <span class="d-block mb-2"><i class="icon-check mr-2"></i> Free wifi</span>
                </p>
                <p><a href="<?= Url::toRoute(['site/detailkost', 'id' => $resultkost->id]); ?>" class="btn btn-primary">Booking</a></p>
              </div>
            </div>
          </div>
          <?php
      }
     ?>
        </div>
      </div>
    </section>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>